const nodemailer = require('nodemailer');

let transporterPromise;

const getTransporter = async () => {
  if (transporterPromise) return transporterPromise;

  transporterPromise = Promise.resolve().then(() => {
    if (process.env.SMTP_HOST) {
      return nodemailer.createTransport({
        host: process.env.SMTP_HOST,
        port: Number(process.env.SMTP_PORT || 587),
        secure: process.env.SMTP_SECURE === 'true',
        auth: process.env.SMTP_USER && process.env.SMTP_PASS
          ? { user: process.env.SMTP_USER, pass: process.env.SMTP_PASS }
          : undefined,
      });
    }

    return nodemailer.createTransport({
      jsonTransport: true,
    });
  });

  return transporterPromise;
};

const sendMail = async ({ to, subject, text, html }) => {
  const transporter = await getTransporter();
  const info = await transporter.sendMail({
    from: process.env.MAIL_FROM || '"CrowdKart" <no-reply@crowdkart.local>',
    to,
    subject,
    text,
    html,
  });

  if (!process.env.SMTP_HOST) {
    console.log('Dev email generated by Nodemailer:', info.message);
  }

  return info;
};

module.exports = {
  sendMail,
};
